version: '3.8'

services:
  db:
    build: ./database
    container_name: postgres
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bridge_network

  api:
    build: ./backend
    container_name: backend
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend/backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge_network

  server:
    build: .
    container_name: server
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge_network

volumes:
  postgres_data:

networks:
  bridge_network:
    driver: bridge
