import { Geist, Geist_Mono, Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";
import Title from "../../components/Title/Title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const balloBhai2 = Baloo_Bhai_2({
  variable: "--font-baloo-bhai-2",  
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${balloBhai2.variable}`}>
      <body>
        <Title/>
        {children}
      </body>
    </html>
  );
}
